#include(GetAllTargets)
#include(DoesTargetUseLinker)

if(CMAKE_CURRENT_SOURCE_DIR STREQUAL CMAKE_SOURCE_DIR)
  message(STATUS "Global default flags:")
  message(STATUS "  C:")
  message(STATUS "          Compiler: ${CMAKE_C_COMPILER_ID} ${CMAKE_C_COMPILER_VERSION} (${CMAKE_C_COMPILER})")
  message(STATUS "          Standard: ${CMAKE_C_STANDARD_DEFAULT}")
  message(STATUS "           Release: ${CMAKE_C_FLAGS} ${CMAKE_C_FLAGS_RELEASE}")
  message(STATUS "    RelWithDebInfo: ${CMAKE_C_FLAGS} ${CMAKE_C_FLAGS_RELWITHDEBINFO}")
  message(STATUS "             Debug: ${CMAKE_C_FLAGS} ${CMAKE_C_FLAGS_DEBUG}")
  message(STATUS "  CXX:")
  message(STATUS "          Compiler: ${CMAKE_CXX_COMPILER_ID} ${CMAKE_CXX_COMPILER_VERSION} (${CMAKE_CXX_COMPILER})")
  message(STATUS "          Standard: ${CMAKE_CXX_STANDARD_DEFAULT}")
  message(STATUS "           Release: ${CMAKE_CXX_FLAGS} ${CMAKE_CXX_FLAGS_RELEASE}")
  message(STATUS "    RelWithDebInfo: ${CMAKE_CXX_FLAGS} ${CMAKE_CXX_FLAGS_RELWITHDEBINFO}")
  message(STATUS "             Debug: ${CMAKE_CXX_FLAGS} ${CMAKE_CXX_FLAGS_DEBUG}")
endif()
