include(GetAllTargets)
#include(DoesTargetUseLinker)

if(CMAKE_CURRENT_SOURCE_DIR STREQUAL CMAKE_SOURCE_DIR)
  message(STATUS "Global default flags:")
  message(STATUS "  C:")
  message(STATUS "          Compiler: ${CMAKE_C_COMPILER_ID} ${CMAKE_C_COMPILER_VERSION} (${CMAKE_C_COMPILER})")
  message(STATUS "          Standard: ${CMAKE_C_STANDARD_DEFAULT}")
  message(STATUS "           Release: ${CMAKE_C_FLAGS} ${CMAKE_C_FLAGS_RELEASE}")
  message(STATUS "    RelWithDebInfo: ${CMAKE_C_FLAGS} ${CMAKE_C_FLAGS_RELWITHDEBINFO}")
  message(STATUS "             Debug: ${CMAKE_C_FLAGS} ${CMAKE_C_FLAGS_DEBUG}")
  message(STATUS "  CXX:")
  message(STATUS "          Compiler: ${CMAKE_CXX_COMPILER_ID} ${CMAKE_CXX_COMPILER_VERSION} (${CMAKE_CXX_COMPILER})")
  message(STATUS "          Standard: ${CMAKE_CXX_STANDARD_DEFAULT}")
  message(STATUS "           Release: ${CMAKE_CXX_FLAGS} ${CMAKE_CXX_FLAGS_RELEASE}")
  message(STATUS "    RelWithDebInfo: ${CMAKE_CXX_FLAGS} ${CMAKE_CXX_FLAGS_RELWITHDEBINFO}")
  message(STATUS "             Debug: ${CMAKE_CXX_FLAGS} ${CMAKE_CXX_FLAGS_DEBUG}")

  get_all_targets(TARGETS)
  set(PARAMETER_FILES)
  foreach(TARGET ${TARGETS})
    set(OUTPUT "Target ${TARGET}\n")
    string(APPEND OUTPUT "               C standard: $<TARGET_GENEX_EVAL:${TARGET},$<TARGET_PROPERTY:${TARGET},C_STANDARD>>\n")
    string(APPEND OUTPUT "             C++ standard: $<TARGET_GENEX_EVAL:${TARGET},$<TARGET_PROPERTY:${TARGET},CXX_STANDARD>>\n")
    string(APPEND OUTPUT "         Compile features: $<TARGET_GENEX_EVAL:${TARGET},$<TARGET_PROPERTY:${TARGET},COMPILE_FEATURES>>\n")
    string(APPEND OUTPUT "          Compile options: $<TARGET_GENEX_EVAL:${TARGET},$<TARGET_PROPERTY:${TARGET},COMPILE_OPTIONS>>\n")
    string(APPEND OUTPUT "      Compile definitions: $<TARGET_GENEX_EVAL:${TARGET},$<TARGET_PROPERTY:${TARGET},COMPILE_DEFINITIONS>>\n")
    string(APPEND OUTPUT "             Link options: $<TARGET_GENEX_EVAL:${TARGET},$<TARGET_PROPERTY:${TARGET},LINK_OPTIONS>>\n")
    string(APPEND OUTPUT "           Link libraries: $<TARGET_GENEX_EVAL:${TARGET},$<TARGET_PROPERTY:${TARGET},LINK_LIBRARIES>>\n")
    string(APPEND OUTPUT " Link interface libraries: $<TARGET_GENEX_EVAL:${TARGET},$<TARGET_PROPERTY:${TARGET},LINK_INTERFACE_LIBRARIES>>\n")
    string(APPEND OUTPUT "      Include directories: $<TARGET_GENEX_EVAL:${TARGET},$<TARGET_PROPERTY:${TARGET},INCLUDE_DIRECTORIES>>\n")
    string(APPEND OUTPUT "\n")

    file(GENERATE OUTPUT ${CMAKE_BINARY_DIR}/Parameters_${TARGET}.txt CONTENT "${OUTPUT}" TARGET ${TARGET})
    list(APPEND PARAMETER_FILES  ${CMAKE_BINARY_DIR}/Parameters_${TARGET}.txt)
  endforeach()

  add_custom_target(print_target_parameters
    COMMAND ${CMAKE_COMMAND} -E cat -- ${PARAMETER_FILES})
endif()
